title: Recommendation System for Food Delivery
description: This page is to showcase my machine learning project on building a recommendation system for food delivery.
show_downloads: true
theme: jekyll-theme-midnight
